Felix45/Questioner

- UI/static/styles/style.css
- UI/templates/registration.html
- Add a create account page that enables a user to register for an account
- Provides a link to the login page if a user has an account already
- A user should be able to register into his or her account 
- A user should be able to navigate` to the login page
#162968484
- Change your working directory to the project directory
`$ cd project_directory`
- Checkout to branch ft-create-account-162968484
`$git checkout branch ft-create-account-162968484`
- Change your working directory to the project directory
- Open the file …
> Ft create account 162968484

- UI/static/styles/style.css
- UI/templates/login.html
- Add a login page that enables a user to login in to his or her account
- Provides a link to the registration page if the user has no account
- Add a login page using html
-  Add a login form to login page
- Add a username, email and login button fields
- Add a navigation link to registration page
- Style the login page using css
** Relevant pivotal tracker stories**
- #162968694
- Change your working directory to project directory
- checkout to branch ft-login-user-162968694
`$ git checkout ft-login-user-162968694`
- Change directory to templates directory
`$ cd …
> Ft login user 162968694

- UI/static/styles/style.css
- UI/templates/admindash.html
- UI/templates/index.html
- Add an admin dashboard page that is displayed when an admin logs on to the application
- Provides links to other admin pages on the application
- Add an admin dashboard page
- Add logged in admin privileged navigation links
- Add a add, delete, view and logout buttons on the admin dashboard
- Style the admin dashboard using css
- #162980926
- checkout to branch ft-admin-dashboard-162980926
`$ git checkout ft-admin-dashboard-162980926`
- Change current working directory to …
> Ft admin dashboard 162980926

- UI/static/styles/style.css
- UI/templates/createmeetup.html
- Add a create meetup page for administrator to add new meetups
- Provides links to other admin pages on the platform on the platform
- Add a create meetup page for adding meetups
- Add a create meetup form for adding meetups
- Add input fields, title , venue , date , image and add meetup button to form
- Add admin navigation links to the create meetup page
- Style the create meetup page 
- #162967834
- Change working directory to project directory
- Checkout to branch ft-create-meetup-162967834
`$ git checkout …
> Ft create meetup 162967834

- UI/static/js/main.js
- UI/static/styles/style.css
- UI/templates/deletemeetup.html
- Adds a delete meetup  page that enables admin to delete a  meetup on the Questioner App
- Provides links to other admin pages on the application
- Add a delete meet up page that allows deletion of meetups.
- Add delete meetup buttons to all meetup entries
- Add delete meetup custom confirm dialog on delete meetup page
- Style the delete meetup page using css 
- Add javascript to control delete meetup page
- Change the working directory to the project directory
- Checkout to branch ft-delete-meetup-162968170
`$ git checkout ft-delete-meetup-162968170`
- Change working …
> #162968170 Builds a delete meetup page

- UI/static/styles/style.css
- UI/templates/profile.html
- Add an user profile page that is displayed when an user logs on to the application
- Add an user profile dashboard page
- Add logged in user navigation links
- Add a questions asked , questions commented section and a top questions button on the user dashboard
- Style the user profile dashboard using css
- #162970914
- checkout to branch ft-user-profile-162970914
`$ git checkout ft-user-profile-162970914`
- Change …
> #162970914 Builds a user profile page

- UI/static/styles/style.css
- UI/templates/postquestion.html
- Adds an up vote , down vote buttons  and reply button to post question
- Add an up vote , down vote and reply buttons to post question
- Style the post question page using css
- #162969781
- checkout to branch ft-up-and-down-vote-162969781
`$ git checkout ft-up-and-down-vote-162969781`
- Open the file postquestion.html using a browser of your …
> #162969781 Adds an up vote and down vote buttons to post question

- UI/static/styles/style.css
- UI/templates/postquestion.html
- Adds a post comment form to  a question on a meetup
- Add a comment section , a comment form and post comment button to post question page
- Style the post comment section on post question page using css
- #162971752
- checkout to branch ft-add-comment-162971752
`$ git checkout ft-add-comment-162971752`
- Open the file postquestion.html using a …
> #162971752 Adds post comment to meet up questions

- UI/static/styles/style.css
- UI/templates/topquestion.html
- Adds a top questions feed  for a users upcoming meetups
- Add a meetup details section , a meetup description section
- Add a top questions feed section next to the meetup details
- Style the top questions feed section on  using css
- #162972367
- checkout to branch ft-top-questions-feed-162972367
`$ git checkout ft-top-questions-feed-162972367` …
> Ft top questions feed 162972367

- UI/templates/admindash.html
- UI/templates/createmeetup.html
- UI/templates/index.html
- UI/templates/login.html
- UI/templates/postquestion.html
- UI/templates/profile.html
- UI/templates/registration.html
- UI/templates/topquestion.html
- Updates navigation links on the UI pages of the application
- Update navigation links on index.html
- Update navigation links on admindash.html
- Update navigation links on login.html
- Update navigation links on registration.html
- Update navigation links on createmeetup.html
- Update navigation links on deletemeetup.html
- Update navigation links on topquestion.html
- Update navigation links on postquestion.html
- Update navigation links on profile.html"
- #163017416
- Change current working …
> #163017416 Fixes navigation links in the application

- UI/templates/meetups.html
- Adds a view all meetups page on the Questioner App
- Provides links to other pages on the application
- Add a all meetups page to view all meetups.
- Style the all meetups page 
- Change the working directory to the project directory
- Checkout to branch ft-view-all-meetups-163027491
`$ git checkout ft-landing-page-163027491`
- Change working directory to UI/templates
- Open the file meetups.html using a browser of your choice
**Desktop View**
**Tablet View**
**Moble View**
> #163027491 Builds a view all meetups page

- UI/templates/createmeetup.html
- Updates navigation links on the createmeetup page of the application
- Update navigation links on createmeetup.html
- #163030514
- checkout to branch bg-delete-meetup-163030514
`$ git checkout bg-delete-meetup-163030514`
- Open the file  createmeetup.html page using a browser of your choice and click on the links
**Desktop View**
- On clicking …
> #163030514 Fixes navigation link on createmeetup page

- .gitignore
- .travis.yml
- requirements.txt
- run.py
- Sets up the directory and file structure for Questioner application
Sets up the directory and file structure for the api
- Checkout to ch-setup-directory-structure-163046390
open the directory as a folder in an editor of your choice
**Directory view**
> #163046390 Sets up directory structure for the api

- app/__init__.py
- app/api/v1/models/users_model.py
- app/api/v1/utils/user_validator.py
- app/api/v1/views/user_view.py
- app/tests/v1/basetest.py
- app/tests/v1/test_users.py
- app/tests/v1/user_list.py
- run.py
- Adds a register user endpoints for user registration
- Add tests for user registration endpoints
- Add endpoints need for user registration
- Checkout to branch ft-create-account-163046437
`$ git checkout ft-create-account-163046437`
- Enter the following commands in to your terminal
```
$ …
```
> #163046437 Adds user registration api

- .travis.yml
- requirements.txt
- Fixes Travis CI bug not installing requirementst.txt
- Update .travis.yml file
- Update requirements.txt file 
- Checkout to branch bg-fix-travis-ci-163100333
`$ git checkout bg-fix-travis-ci-163100333`
open the reuirements.txt and .travis.yml they should look like the images below …
> [finishes #163100333] fixes bug in travis.yml

- app/__init__.py
- app/api/v1/models/meetups_model.py
- app/api/v1/views/meetups_view.py
- app/tests/v1/test_meetups.py
- Adds a create meetup endpoint for adding a meetup record
- Add tests for create meetup endpoint 
- Add endpoint creating a meetup record
- Checkout to branch ft-meetup-api-163046496 
`$ git checkout ft-meetup-api-163046496 `
- Enter the following commands in to your terminal
```
$ export …
```
> #163046496 creates a create meetup endpoint 

- app/api/v1/models/meetups_model.py
- app/api/v1/views/meetups_view.py
- app/tests/v1/test_meetups.py
- Adds a view specific meetup endpoint for getting a meetups records
- Add tests for viewing a specific meetup
- Add endpoint viewing a meetup record
- Checkout to branch ft-view-specific-163047414
`$ git checkout ft-view-specific-163047414 `
- Enter the following commands in to your terminal …
> #163047414 view specific meetup

- app/api/v1/models/users_model.py
- Fixes Travis CI bug remove python 2.7 code syntax
- Update users_model.py in models directory
- Checkout to branch bg-travis-ci-error-163100333
`$ git checkout bg-travis-ci-error-163100333`
- Open the file users_model.py under the models directory.
> [finishes #163117063] updated users model file

- app/__init__.py
- app/api/v1/models/meetups_model.py
- app/api/v1/models/users_model.py
- app/api/v1/utils/user_validator.py
- app/api/v1/views/meetups_view.py
- app/api/v1/views/user_view.py
- app/tests/v1/basetest.py
- app/tests/v1/test_meetups.py
- app/tests/v1/test_users.py
- app/tests/v1/user_list.py
- run.py
- Fixes Travis CI bug mixed tab and spaces
- Update all files in application project that have mixed spaces and tabs
- Checkout to branch bg-travis-ci-tabs-spaces-error-163118741
`$ git checkout bg-travis-ci-tabs-spaces-error-163118741`
open .py file in the application directory and notice the …
> #163118741 fixes the mixed tabs and spaces error causing travis build fail

- app/tests/v1/test_meetups.py
- app/tests/v1/test_users.py
- Fixes Travis CI bug tests not running as expected
- Fix test to expect string response not object based response
`$ cd Questioner/app/tests/v1`
- Checkout to branch bg-fix-travis-test-error-163127427
`$ git checkout bg-fix-travis-test-error-163127427`
Open the files test_users.py and test_meetups.py the …
> #163127427 fixes travis test error

- .coveralls.yml
- .travis.yml
- README.md
- Adds Travis CI badge
- Adds Coveralls badge
- Adds Code climate badge
- Improves content of README.md
- Add Travis CI markdown badge to readme file
- Add Coveralls badge to readme file
- Add Codeclimate badge to readme file
- Improve the content of readme file
`$ cd Questioner/app/tests/v1`
- Checkout to …
> #163132492 Adds badges and test commands to readme

- app/tests/v1/test_users.py
- Fixes Travis CI bug test password error test case
- Fix test to expect string response not object based response
`$ cd Questioner/app/tests/v1`
- Checkout to branch bg-fix-passwordt-error-163140039
`$ git checkout bg-fix-passwordt-error-163140039`
Open the files test_users.py and test_meetups.py the …
> [finishes #163140039] fiixes password error test case

- app/tests/v1/test_users.py
- Fixes invalid syntax error that appear in test_users.py
- Fix invalid syntax error that appear in test_users.py
`$ cd Questioner/app/tests/v1`
- Checkout to branch bg-fix-password-error-163140039
`$ git checkout bg-fix-password-error-163140039`
- Run command
`pytest --cov app`
Notice the error that appears on …
> #163140277 fixes invalid syntax error in test_users.py

- app/api/v1/models/meetups_model.py
- app/api/v1/views/meetups_view.py
- app/tests/v1/test_meetups.py
- Adds a create a voteup and downvote question endpoint
- Add tests for voteup and downvote a question endpoint
- Add an endpoint for voteup and downvote a question endpoint
- Checkout to branch ft-upvote-downvote-question-163047199
`$ git checkout ft-upvote-downvote-question-163047199 `
- …
> #163047199 Adds upvote downvote question endpoint

- app/api/v1/models/meetups_model.py
- app/api/v1/views/meetups_view.py
- app/tests/v1/test_meetups.py
- Adds a respond please response to meetups
- Add tests for create a respond please to meetups endpoint
- Add a create  a respond please to meetups endpoint
- Checkout to branch ft-confirm-attendance-rsvp-163050338
`$ git checkout ft-confirm-attendance-rsvp-163050338 `
- Enter the following …
> #163050338 confirm meetup attendance rsvp 

- app/api/v1/models/meetups_model.py
- app/api/v1/models/users_model.py
- app/api/v1/views/meetups_view.py
- app/tests/v1/test_meetups.py
- Adds a fetch single question record endpoint
- Add tests for fetching a question record
- Add an endpoint for creating a question record
- Checkout to branch ft-fetch-single-question-163221072
`$ git checkout ft-fetch-single-question-163221072 `
- Enter the following commands into your …
> #163221072 fetch a single question

- app/.env
- app/api/v2/utils/user_validator.py
- app/api/v2/views/meetups_view.py
- app/api/v2/views/user_view.py
- app/dbconnection.py
- app/tests/v2/basetest.py
- app/tests/v2/test_meetups.py
- app/tests/v2/test_questions.py
- app/tests/v2/test_users.py
- app/tests/v2/user_list.py
- Sets up the database and directory structure to be used by the application
- Sets up the database to be used by the application
- Sets up a version 2 directory of the application endpoints
- Sets up a version 2 directory of the application tests
- Checkout to ch-setup-database-163222546
open the directory as a folder in an editor of your choice or use `Vscode`
- Change directory to `cd app/tests/v2` to view the unit tests
- Change directory to `cd app/api/v2` to view the new application files for …
> #163222546 Sets up database and directory structure

- app/__init__.py
- app/api/v1/models/users_model.py
- app/api/v2/models/base_model.py
- app/api/v2/models/users_model.py
- app/api/v2/utils/database_helper.py
- app/api/v2/views/user_view.py
- app/dbconnection.py
- Adds a register user endpoints for user registration that uses a database 
- Add tests for user registration endpoints
- Add endpoints need for user registration
- Checkout to branch ft-create-account-163222777 
`$ git checkout ft-create-account-163222777 `
- Enter the following commands in …
> #163222777 creates a create an account v2 endpoint

- app/api/v1/utils/user_validator.py
- app/api/v2/models/users_model.py
- app/api/v2/utils/database_helper.py
- app/dbconnection.py
- Adds a login user endpoint that uses a database to store data.
- Add tests for user_login  
- Add endpoint view for user login
- Add JWT authentication to user login endpoint
- Checkout to branch ft-user-login-163223005
`$ git checkout ft-user-login-163223005 `
- Enter the following commands …
> #163223005 Creates a user login endpoint

- app/__init__.py
- app/api/v2/models/meetups_model.py
- app/api/v2/models/users_model.py
- app/api/v2/utils/database_helper.py
- app/api/v2/views/meetups_view.py
- app/dbconnection.py
- Adds a create meetup endpoint record to store in the database
- Add tests for creating meetup endpoint 
- Add endpoint for creating a meetup record
- Checkout to branch ft-create-meetup-163281826
`$ git checkout ft-create-meetup-163281826`
- Enter the following commands into your …
>  #163281826 Adds an admin create meetup endpoint

- app/api/v2/models/meetups_model.py
- app/api/v2/utils/database_helper.py
- Adds a delete meetup record from the database
- Add tests for delete meetup record feature
- Add endpoint for an admin can delete meetup record
- Checkout to branch ft-delete-meetup-163223396
`$ git checkout ft-delete-meetup-163223396 `
- Enter the following commands into your terminal …
> #163343934 View a specific meetup 

- app/api/v2/models/meetups_model.py
- app/api/v2/utils/database_helper.py
- Adds a view all upcoming meetups endpoint 
- Add tests for view all upcoming meetup endpoint 
- Add endpoint view all upcoming  meetup records
- Checkout to branch ft-view-all-meetups-163047527
`$ git checkout ft-view-all-meetups-163047527 `
- Enter the following commands into your …
> #163344901 view all upcoming meetups

- app/.env
- app/api/v2/models/questions_model.py
- app/api/v2/utils/database_helper.py
- app/api/v2/views/questions_view.py
- app/dbconnection.py
- Adds a vote question endpoint 
- Add tests for an upvote or downvote question on a meetup endpoint 
- Add endpoint upvoting or downvoting a question on a  meetup record
- Checkout to branch ft-vote-question-163346855
`$ git checkout ft-vote-question-163346855 `
- Enter the following …
> #163346855 Vote a question on a meetup endpoint 

- .travis.yml
- app/__init__.py
- app/api/v2/models/comments_model.py
- app/api/v2/models/users_model.py
- app/api/v2/utils/database_helper.py
- app/api/v2/views/comments_view.py
- app/dbconnection.py
- app/tests/v1/basetest.py
- app/tests/v2/basetest.py
- app/tests/v2/test_comments.py
- app/tests/v2/test_questions.py
- Adds a user can comment on a question 
- Adds a user can comment on a question
- Adds an endpoint for a user can comment on a question
- Checkout to branch ft-user-comment-question-163223209
`$ git checkout ft-user-comment-question-163223209 `
- Enter the following commands into your …
> #163223209 Adds a user can comment on a question 

- app/api/v2/models/users_model.py
- Fixes a user can register on the questioner application
- Remove `isadmin` field from the body of the request
- Fix the images and tags list provided in during meetup creation.
- Checkout to branch bg-fix-user-registration-163497822
`$ git checkout bg-fix-user-registration-163497822 `
**Related pivotal tracker stories**
[Implement LFA feedback on user registration](https://www.pivotaltracker.com/n/projects/2235209/stories/163497822)
Open a test client of your choice, preferably `Postman`. Make a `POST` request to the following URL  http://127.0.0.1:5000/api/v2/users/add using the following data.
```
{
"firstname": "Felix",
"lastname": "Ouma",
"othername": "Okish", …
```
> #163497822 Fix user registration

- app/api/v2/models/comments_model.py
- app/api/v2/models/meetups_model.py
- app/api/v2/models/questions_model.py
- app/api/v2/models/users_model.py
- app/api/v2/utils/database_helper.py
- app/tests/v2/test_questions.py
> #163498415 Fix meetups tags and images

- UI/static/styles/style.css
Make the footer stick to the bottom of the page
> update the footer styles

- UI/static/styles/style.css
Make footer fill entire screen width
> Make footer fill entire screen width

- README.md
> In this pull request I
- updated the readme file to give a brief description of this project.
> Update project descriptpion and app live link

- LICENCE
> In this pull request I
- Added the MIT license to the project.
> Add MIT Licence to project

- UI/templates/index.html
- UI/templates/meetups.html
> In this pull request I
- Fixed the appearance of the meetup cards on the home page for small devices
> Milestone: Update meetup card layout on mobile devices
